// Automation event taxonomy — aligns with funnel events but automation-specific
export type AutomationEventName =
  | "order_created"
  | "payment_received"
  | "payment_failed"
  | "payment_timeout"
  | "storefront_published"
  | "product_created"
  | "first_sale_completed"
  | "onboarding_completed"
  | "creator_inactive_7d"
  | "creator_inactive_30d"
  | "ai_generation_completed"
  | "storefront_unpublished"
  | "low_product_count"
  | "whatsapp_message_received"
  | "store_schema_updated"
  | "weekly_digest_requested"
  | "checkout_started"
  | "checkout_abandoned"
  | "lead_scored"
  // ── Intelligence events ──────────────────────────────────────────────
  | "creator_health_degraded"
  | "creator_revenue_drop"
  | "creator_revenue_forecast_updated"
  | "creator_growth_detected"
  | "creator_churn_risk"
  | "creator_engagement_drop"
  | "customer_high_value"
  | "customer_reengagement_needed"
  | "workflow_retry_spike"
  | "workflow_at_risk"
  | "ai_cost_spike"
  | "ai_budget_risk"
  | "recommendation_generated"
  // ── Coordination events ──────────────────────────────────────────────
  | "creator_monetization_opportunity"
  | "creator_high_influence_detected"
  | "workflow_priority_elevated"
  // ── Marketplace intelligence events ──────────────────────────────────
  | "marketplace_health_updated"
  | "marketplace_conversion_drop"
  | "storefront_performance_risk"
  | "creator_repeat_customer_growth"
  // ── Ecosystem events ─────────────────────────────────────────────────
  | "ecosystem_revenue_growth"
  | "ecosystem_retention_risk"
  // ── Trust intelligence events ─────────────────────────────────────────
  | "creator_trust_improved"
  | "creator_trust_degraded"
  | "creator_high_reliability"
  | "creator_dispute_risk"
  | "creator_reputation_drop"
  | "creator_network_growth_detected"
  | "creator_collaboration_opportunity"
  | "creator_fulfillment_risk"
  | "customer_trust_risk"
  | "customer_fraud_risk"
  | "suspicious_checkout_detected"
  | "dispute_spike_detected"
  | "marketplace_integrity_risk"
  | "marketplace_trust_degradation"
  // ── Discovery intelligence events ────────────────────────────────────
  | "creator_trending"
  | "creator_discovery_boost"
  | "storefront_discovery_accelerated"
  | "storefront_recommendation_generated"
  | "customer_match_high_confidence"
  | "customer_discovery_accelerated"
  | "customer_referral_detected"
  | "customer_loyalty_accelerated"
  | "conversion_priority_high"
  // ── Ecosystem collaboration + expansion events ───────────────────────
  | "creator_referral_opportunity"
  | "ecosystem_network_acceleration"
  | "ecosystem_monetization_opportunity"
  | "category_high_growth"
  | "ecosystem_expansion_opportunity"
  | "geography_expansion_opportunity"
  | "creator_network_scaling"
  // ── Economy intelligence events ──────────────────────────────────────────
  | "creator_high_growth"
  | "creator_revenue_accelerated"
  | "creator_profitability_growth"
  | "creator_scaling_opportunity"
  | "repeat_purchase_accelerated"
  | "economy_health_updated"
  | "creator_ecosystem_influence_growth"
  // ── Retention intelligence events ─────────────────────────────────────────
  | "creator_retention_risk"
  | "customer_churn_risk"
  | "customer_retention_recovery_needed"
  | "customer_repeat_purchase_growth"
  | "customer_community_growth"
  | "loyalty_acceleration"
  | "engagement_decay"
  // ── Scaling coordination events ───────────────────────────────────────────
  | "marketplace_scaling_bottleneck"
  | "creator_acquisition_opportunity"
  | "monetization_anomaly"
  | "ecosystem_integrity_risk"
  | "localized_monetization_opportunity"
  | "region_high_growth"
  | "discovery_optimization_recommended"
  | "scaling_governance_alert"

export interface AutomationEvent {
  name: AutomationEventName
  creatorId: string
  payload: Record<string, unknown>
  idempotencyKey?: string
}
