import type { StorePreset } from "../schema/types"

export const STORE_PRESETS: StorePreset[] = [
  {
    id: "lummy",
    name: "Lummy Default",
    preview: "#6C4EF3",
    description: "The classic Lummy look — electric purple with clean typography",
    theme: {
      accent: "#6C4EF3",
      accentFg: "#ffffff",
      font: "inter",
      layout: "grid-3",
      radius: "lg",
      shadow: "md",
      buttonStyle: "default",
    },
  },
  {
    id: "midnight",
    name: "Midnight Luxury",
    preview: "#F59E0B",
    description: "Dark, editorial, aspirational — for premium fashion and beauty",
    theme: {
      accent: "#F59E0B",
      accentFg: "#000000",
      font: "playfair",
      layout: "grid-2",
      radius: "xl",
      shadow: "lg",
      buttonStyle: "pill",
    },
  },
  {
    id: "africa",
    name: "Bright Market",
    preview: "#F97316",
    description: "Warm, vibrant, energetic — inspired by independent market culture",
    theme: {
      accent: "#F97316",
      accentFg: "#ffffff",
      font: "poppins",
      layout: "grid-3",
      radius: "xl",
      shadow: "md",
      buttonStyle: "pill",
    },
  },
  {
    id: "minimal",
    name: "Clean Minimal",
    preview: "#111111",
    description: "No distractions — bold typography, maximum focus on products",
    theme: {
      accent: "#111111",
      accentFg: "#ffffff",
      font: "inter",
      layout: "grid-3",
      radius: "sm",
      shadow: "none",
      buttonStyle: "sharp",
    },
  },
  {
    id: "emerald",
    name: "Emerald Market",
    preview: "#10B981",
    description: "Fresh and confident — great for food, wellness, and natural products",
    theme: {
      accent: "#10B981",
      accentFg: "#ffffff",
      font: "poppins",
      layout: "grid-3",
      radius: "lg",
      shadow: "sm",
      buttonStyle: "default",
    },
  },
  {
    id: "rose",
    name: "Rose Studio",
    preview: "#F43F5E",
    description: "Soft, romantic, editorial — perfect for beauty, lifestyle and fashion",
    theme: {
      accent: "#F43F5E",
      accentFg: "#ffffff",
      font: "playfair",
      layout: "grid-2",
      radius: "xl",
      shadow: "md",
      buttonStyle: "pill",
    },
  },
]
